name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
    - name: Install CocoaPods dependencies
      run: |
        sudo gem install cocoapods
        pod install

    - name: Build and Test
      run: |
        xcodebuild clean build -workspace AppForceUpdateApp.xcworkspace -scheme AppForceUpdateApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
        xcodebuild test -workspace AppForceUpdateApp.xcworkspace -scheme AppForceUpdateApp -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
